[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
qubit = "0.0.8"
tokio = { version = "1.37.0", features = ["full"] }
hyper = { version = "0.14.10", features = ["server"] }
axum = "0.6.20"
ts-rs = "8.1.0"
