// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PollOverview = { id: string, name: string, description: string, options: Array<string>, };